version: '3.8'

services:
  nougat:
    build:
      context: .
      dockerfile: Dockerfile
    image: nougat-service
    container_name: nougat-container
    restart: unless-stopped
    ports:
      - "8503:8503"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./data:/workspace/data  # Optional: mount a data directory if needed
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant-container
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z